version: '3'

services:
  app:
    image: quay.io/wantedly/grpc-gateway-study-dev:latest
    build: .
    volumes:
      - ..:/app
      # - vendor:/app/vendor
      - dep_cache:/go/pkg/dep
      - tmp:/app/tmp
      - ~/.ssh:/host_ssh:ro
    ports:
      - 3000:3000
    extra_hosts:
      localhost: "${DOCKER_HOST_IP}"
    command: tail -f /dev/null

volumes:
  vendor:
  dep_cache:
  tmp:
